defaults:
  - _self_
  - override hydra/launcher: joblib

api_key: ${oc.env:API_KEY}
api_url: ${oc.env:API_URL}
model_name: gpt-5.4-mini
generation_model_name: ???
llm_cache: false
final_only: false

llm:
  temperature: 0.2
  max_tokens: 32000
  model_kwargs:
    reasoning_effort: "medium"

case_name: ??? # ["pl_age", "pl_personal_rights", "pl_medical_errors"]

state_dir: multirun/generated_schemas/${generation_model_name}/${case_name}/
eval_data_dir: data/eval/
case_dir: ${eval_data_dir}/${case_name}

output_subdir: evaluation/${model_name}/${case_name}
output: ${hydra:runtime.output_dir}

hydra:
  launcher:
    n_jobs: 4
  run:
    dir: outputs/${output_subdir}
  sweep:
    dir: outputs/
    subdir: ${output_subdir}

  sweeper:
    params:
      case_name: pl_age,pl_personal_rights
