defaults:
  - _self_
  - case: ???

api_key: ${oc.env:API_KEY}
api_url: ${oc.env:API_URL}
# model_name: gpt-5.2
model_name: gpt-5-nano
# model_name: llama-4-scout-17b
wv_collection_name: LegalDocuments
llm_cache: false

llm:
  temperature: 0.2
  max_tokens: 32000
  model_kwargs:
    reasoning_effort: "medium"

schema_generator:
  max_refinement_rounds: 4
  min_refinement_rounds: 1
  max_data_refinement_rounds: 3
  min_data_refinement_rounds: 1
  data_assessment_top_k: 50
  data_assessment_num_examples: 2
  data_assessment_random_seed: 17

output_subdir: generated_schemas/${model_name}/${case.name}/maxrr_${schema_generator.max_refinement_rounds}_minrr_${schema_generator.min_refinement_rounds}_maxdrr_${schema_generator.max_data_refinement_rounds}_mindrr_${schema_generator.min_data_refinement_rounds}_dane_${schema_generator.data_assessment_num_examples}
output: ${hydra:runtime.output_dir}

hydra:
  run:
    dir: outputs/${output_subdir}
  sweep:
    dir: multirun/
    subdir: ${output_subdir}
    
  sweeper:
    params:
      schema_generator.max_refinement_rounds: 2,3,4
      schema_generator.min_refinement_rounds: 1,2
      schema_generator.max_data_refinement_rounds: 2,3,4
      schema_generator.min_data_refinement_rounds: 1,2
      schema_generator.data_assessment_num_examples: 1,2,3
